### ISSUE TITLE
DS918+ DSM 7.1.1-42962 Update 1 无效

### ISSUE THREAD

**Issue by linukun** [jinlife/Synology_Photos_Face_Patch#10]
使用补丁后失联，重启后需要重装。试了两次。

**Comment by jinlife** [comment]
建议提问题的时候将使用环境，使用步骤贴上来。

测试过42962 up1没问题。
猜测可能是用户使用了不好用的显卡驱动，或者用了非常新的CPU。建议如果是pve或unraid之类，直接用虚拟显卡就行了。不要用显卡，除非能正确驱动。
