### ISSUE TITLE
synofoto-bin-team-library-tool

### ISSUE THREAD

**Issue by MartinKuhl** [jinlife/Synology_Photos_Face_Patch#13]
Hi,
I am on DSM version 7.1.1 U2 and have Photos in version 1.3.0.
I copied your patch in the mentioned directory but I receive the following error in /vat/log/messages:
synofoto-bin-team-library-tool[17496]: /source/synofoto/src/lib/io/channel.cpp:79 channel[/run/synofoto/task-center.socket] construct failed: connect: No such file or directory

The Photos app is not creating any entry within the persons folder.

Any ideas?

**Comment by jinlife** [comment]
Hello,
That is not the error of face recognization, it might be related with team sharing.
Face extraction errors are following logs:
```
synofoto-face-extraction[30626]: uncaught thread task exception /source/synofoto/src/daemon/plugin/plugin_worker.cpp:90 plugin init failed: /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-face.so
```
Please add dozens of pictures and re-index, then wait for few minutes. 
BTW: do not use libsynosdk.so.7 at first.

**Comment by MartinKuhl** [comment]
After restarting the App face recognization is working!
