### ISSUE TITLE
1.3.3-0330不能正常识别

### ISSUE THREAD

**Issue by Jayatubi** [jinlife/Synology_Photos_Face_Patch#16]
DSM 7.1.1-42962
Photos 1.3.3-0330
ESXI 6.7U3：4核 CPU，8G RAM，无核显

替换了so之后，不会卡住”还有N张照片待发现“的进度，但是进度走完之后也没有任何结果出来。全程face-extraction几乎没有CPU的占用开销。

**Comment by jinlife** [comment]
ESXI配置问题，具体没研究过。很多原本不需要补丁的CPU，在ESXI上都用不了。
建议换个虚拟机平台或者物理安装群晖。

**Comment by Jayatubi** [comment]
更新一下现象：实测人脸识别是有效的，但是不会自动出现Photos的“人物”相册里面，而是单独点击某个照片的时候，会在信息面面板里面出现被识别出来的人脸。点击这些人脸，再输入一个名字，才会在”人物“相册里面出现。

之前DSM 6的人脸识别似乎会自动收集到人物相册，但是DSM 7没有，不知道是功能修改了，还是有其他错误。

**Comment by jinlife** [comment]
这是个特殊问题，正常DSM7打上补丁没这情况的，“人物”会出现这是谁，然后需要改名字。如果有兴趣可以去上网查查有没有人碰到类似情况，或者试试同样的硬件，换其他非ESXI有没有此问题。
或者现在这样貌似也能用了，能命名的人物也不会太多，命名之后也很少改，基本就稳定了。可以试试命名后再传几个新照片能不能归类到命名的人物下，如果能归类那也凑合能用。

**Comment by WadeChenn** [comment]
> 更新一下现象：实测人脸识别是有效的，但是不会自动出现Photos的“人物”相册里面，而是单独点击某个照片的时候，会在信息面面板里面出现被识别出来的人脸。点击这些人脸，再输入一个名字，才会在”人物“相册里面出现。
> 
> 之前DSM 6的人脸识别似乎会自动收集到人物相册，但是DSM 7没有，不知道是功能修改了，还是有其他错误。

请问后面有解决这个问题嘛.遇到一样的情况

**Comment by Jayatubi** [comment]
后来装了3615之后就好了
