### ISSUE TITLE
esxi6.7，dsm7.0。8代i5

### ISSUE THREAD

**Issue by l625166686** [jinlife/Synology_Photos_Face_Patch#2]
大佬，你好。根据教程一步一步做了，结果是人脸识别一直待发现（3张照片，40个小时了）。esxi6.7，dsm7.0。8代i5。

**Comment by jinlife** [comment]
这个应该是esxi虚拟机的问题，可以虚拟一个DS3615xs看看，如果DS3615xs都不行。那就不是GPU的问题了。
建议至少都虚拟4个CPU核心给群晖。
