### ISSUE TITLE
人脸识别成功了，但是jellyfin无法硬解了

### ISSUE THREAD

**Issue by DavidHuang1996** [jinlife/Synology_Photos_Face_Patch#20]
pve7.4版本，虚拟的群晖7.2，ARPl引导，参照这个教程https://wp.gxnas.com/11592.html/comment-page-4，使用了您的补丁，人脸识别也成功了，但是jellyfin无法硬解了，emby也是，有点头疼，删除了补丁过，重启过，卸载重装过photos，jellyfin都不行，大佬有解决办法吗？

**Comment by DavidHuang1996** [comment]
配置是，b150m+qnct

**Comment by jinlife** [comment]
这里的补丁只改了photos内部的lib文件，只会影响photos应用。跟别的应用一点关系都没有。Jellyfin无法硬解应该是核显没驱动，这个要去网上找找核显相关的文章看看。

**Comment by DavidHuang1996** [comment]
好的，谢谢
