### ISSUE TITLE
Need patch for Photos v.1.6.2-0710 

### ISSUE THREAD

**Issue by dj-nsk** [jinlife/Synology_Photos_Face_Patch#24]
Hi! There is a new version of Photos, could you release a patch for it? Thanks!

**Comment by chenyifei553** [comment]
yes，I tried for an hour and cannot solve it ，can you upload a patch for v1.6.2-0710?

**Comment by Lighthouseh** [comment]
Yeah, I'm looking forward to it too. I have not updated yet.

**Comment by jinlife** [comment]
Updated, please check if it works. 
Actually, it seems 1.6.1 and 1.6.2 have same files, so the patch is the same.

**Comment by chenyifei553** [comment]
It works，thanks a lot

**Comment by Lighthouseh** [comment]
Everyone on the People album disappeared. I'm trying reindex.

**Comment by jimcchi** [comment]
It works

Once the new version is installed, type this code with ssh

`synopkgctl stop SynologyPhotos
cp -f /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so-bak
cp -f /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0 /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0-bak
wget --no-check-certificate https://mirror.ghproxy.com/https://github.com/jinlife/Synology_Photos_Face_Patch/releases/download/1.6.2-0710/libsynophoto-plugin-platform.so
wget --no-check-certificate https://mirror.ghproxy.com/https://github.com/jinlife/Synology_Photos_Face_Patch/releases/download/1.6.2-0710/libsynophoto-plugin-platform.so.1.0
cp -f libsynophoto-plugin-platform.so /var/packages/SynologyPhotos/target/usr/lib/
cp -f libsynophoto-plugin-platform.so.1.0 /var/packages/SynologyPhotos/target/usr/lib/
chmod +x /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so
chmod +x /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0
chown SynologyPhotos:SynologyPhotos /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so
chown SynologyPhotos:SynologyPhotos /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0
synopkgctl start SynologyPhotos`

**Comment by Lighthouseh** [comment]
> It works
> 
> Once the new version is installed, type this code with ssh
>

Didn't work, I reinstalled photos, copied 2 files libsynophoto-plugin-platform, chmod and chown (which previous versions did not need). Try reindexing. Now in people it says No Items.

**Comment by Lighthouseh** [comment]
After trying a few times, it worked again.  But everyone's names are gone.  Now I have to name each identity group.

**Comment by tone88** [comment]
> After trying a few times, it worked again. But everyone's names are gone. Now I have to name each identity group.

I'm in the same situation. It's really annoying if it happens every time I upgrade.

**Comment by jinlife** [comment]
it seems works, so I will close it.
