### ISSUE TITLE
Face Mappings get lost

### ISSUE THREAD

**Issue by thorfrigel** [jinlife/Synology_Photos_Face_Patch#25]
After upgrading to DSM 7.2.1. and patch Photos 1.6.1-0641 all my face mappings got lost and had to reapply manually.
The same happened to 1.6.2-0710. Any hints?

**Comment by tone88** [comment]
+1

**Comment by tuyennn** [comment]
+1 and I cannot get the face mapping back while applying the patch again. Now it's blank (Photo 1.6.2-0710 - DSM 7.2.1)

**Comment by Lighthouseh** [comment]
> +1 và tôi không thể lấy lại bản đồ khuôn mặt trong khi áp dụng lại bản vá. Bây giờ nó trống rỗng (Ảnh 1.6.2-0710 - DSM 7.2.1)
You just need to wait 1 night (if you have a lot of photos), the faces will appear again. However their names disappeared.

**Comment by jinlife** [comment]
Well, I assume some of you are not using official Synology devices.
If there is only basic forward update for Synology Photos, the face should be kept. Otherwise, it will be bugs in Photos. The face patch has nothing to do with the internal database.

Also, it looks like there is DSM version change, you guys should be careful with what you have done.

Photos will save face result into internal built-in postgrel database which is hiden from end users.  So if you have done any reimage of DSM, I don't know what the loader will do. It might keep the database or reacreate a brand new one. So please don't update DSM if you want a stable Photos, espercially if you are not official Synology device.

Also, please do not uninstall photos. It will clean up the postgrel database but not your photo. Just upgrade.

**Comment by tuyennn** [comment]
@jinlife I've done the reindexing all the library, the peoples are now appeared on the board.
```
synofoto-bin-index-tool -t reindex -i
```

**Comment by IV16SL** [comment]
`synopkgctl stop SynologyPhotos
chmod +x /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so
chmod +x /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0
chown SynologyPhotos:SynologyPhotos /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so
chown SynologyPhotos:SynologyPhotos /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0
synopkgctl start SynologyPhotos`
then rebuild the index can solve this.

**Comment by jinlife** [comment]
Thank you guys for the updating.
1. Sometimes, the operation may delete the postgrel database, but there are still some hidden folders in eaDir, so it may not be clean enough for the photo to not trigger the face on its own. Reindex would be the best way to force face recognition.
2. Sometimes, you need to chmod and chown if you deleted or moved files. But if you just copy it to backup then overwrite it. You don't need chmod and chown.

**Comment by gzjackar** [comment]
Hi Jinlife: I tried 2 ways you mentioned below without any error, but it only can enable the object recognition and the face recogniion still pending the 156 photos for quite a long time, a few days. Could you give me some guidance , 918+ 1.6.2-0710

Way 1:
synopkgctl stop SynologyPhotos
cp -f /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so-bak
cp -f /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0 /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0-bak
cd /tmp
wget --no-check-certificate https://mirror.ghproxy.com/https://github.com/jinlife/Synology_Photos_Face_Patch/releases/download/1.6.2-0710/libsynophoto-plugin-platform.so
wget --no-check-certificate https://mirror.ghproxy.com/https://github.com/jinlife/Synology_Photos_Face_Patch/releases/download/1.6.2-0710/libsynophoto-plugin-platform.so.1.0
cp -f libsynophoto-plugin-platform.so /var/packages/SynologyPhotos/target/usr/lib/
cp -f libsynophoto-plugin-platform.so.1.0 /var/packages/SynologyPhotos/target/usr/lib/
chmod +x /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so
chmod +x /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0
chown SynologyPhotos:SynologyPhotos /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so
chown SynologyPhotos:SynologyPhotos /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0
synopkgctl start SynologyPhotos

Way 2:
Refered to this command, it worked well on Mar 16, 2024
wget https://raw.githubusercontent.com/jinlife/Synology_Photos_Face_Patch/main/bin/PatchELFSharp-Linux64/PatchELFSharp -O PatchELFSharp
chmod +x PatchELFSharp
./PatchELFSharp "/usr/lib/libsynosdk.so.7" "SYNOFSIsRemoteFS" "B8 00 00 00 00 C3"
# support face and concept


![image](https://github.com/jinlife/Synology_Photos_Face_Patch/assets/48777459/0cfbeddc-6c79-4698-acf7-123fa99ca36e)

./PatchELFSharp "/var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so" "_ZN9synophoto6plugin8platform20IsSupportedIENetworkEv" "B8 00 00 00 00 C3"
# force to support concept
./PatchELFSharp "/var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so" "_ZN9synophoto6plugin8platform18IsSupportedConceptEv" "B8 01 00 00 00 C3"
# force no Gpu
./PatchELFSharp "/var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so" "_ZN9synophoto6plugin8platform23IsSupportedIENetworkGpuEv" "B8 00 00 00 00 C3"

**Comment by jinlife** [comment]
> Hi Jinlife: I tried 2 ways you mentioned below without any error, but it only can enable the object recognition and the face recogniion still pending the 156 photos for quite a long time, a few days. Could you give me some guidance , 918+ 1.6.2-0710
> 
> Way 1: synopkgctl stop SynologyPhotos cp -f /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so-bak cp -f /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0 /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0-bak cd /tmp wget --no-check-certificate https://mirror.ghproxy.com/https://github.com/jinlife/Synology_Photos_Face_Patch/releases/download/1.6.2-0710/libsynophoto-plugin-platform.so wget --no-check-certificate https://mirror.ghproxy.com/https://github.com/jinlife/Synology_Photos_Face_Patch/releases/download/1.6.2-0710/libsynophoto-plugin-platform.so.1.0 cp -f libsynophoto-plugin-platform.so /var/packages/SynologyPhotos/target/usr/lib/ cp -f libsynophoto-plugin-platform.so.1.0 /var/packages/SynologyPhotos/target/usr/lib/ chmod +x /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so chmod +x /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0 chown SynologyPhotos:SynologyPhotos /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so chown SynologyPhotos:SynologyPhotos /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0 synopkgctl start SynologyPhotos
> 
> Way 2: Refered to this command, it worked well on Mar 16, 2024 wget https://raw.githubusercontent.com/jinlife/Synology_Photos_Face_Patch/main/bin/PatchELFSharp-Linux64/PatchELFSharp -O PatchELFSharp chmod +x PatchELFSharp ./PatchELFSharp "/usr/lib/libsynosdk.so.7" "SYNOFSIsRemoteFS" "B8 00 00 00 00 C3"
> 
> # support face and concept
> ./PatchELFSharp "/var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so" "_ZN9synophoto6plugin8platform20IsSupportedIENetworkEv" "B8 00 00 00 00 C3"
> 
> # force to support concept
> ./PatchELFSharp "/var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so" "_ZN9synophoto6plugin8platform18IsSupportedConceptEv" "B8 01 00 00 00 C3"
> 
> # force no Gpu
> ./PatchELFSharp "/var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so" "_ZN9synophoto6plugin8platform23IsSupportedIENetworkGpuEv" "B8 00 00 00 00 C3"
> 
> ![image](https://private-user-images.githubusercontent.com/48777459/313440045-0cfbeddc-6c79-4698-acf7-123fa99ca36e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzA1ODUsIm5iZiI6MTcxMDkzMDI4NSwicGF0aCI6Ii80ODc3NzQ1OS8zMTM0NDAwNDUtMGNmYmVkZGMtNmM3OS00Njk4LWFjZjctMTIzZmE5OWNhMzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDEwMjQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MDE3NzQ5NjgxYTk3ODY3Njc0N2M3NjQyN2Y3NjkyMTM1NGU4YjY3MmMzOTM4NGE4NGNiZThlY2VkZDZkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EfsvKIOpFWCgH0oqGPDGDk5uaIVKJlwO1rf6fkhVC5w)

I have no idea, might be other reasons.

**Comment by gzjackar** [comment]
> > Hi Jinlife: I tried 2 ways you mentioned below without any error, but it only can enable the object recognition and the face recogniion still pending the 156 photos for quite a long time, a few days. Could you give me some guidance , 918+ 1.6.2-0710
> > Way 1: synopkgctl stop SynologyPhotos cp -f /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so-bak cp -f /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0 /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0-bak cd /tmp wget --no-check-certificate https://mirror.ghproxy.com/https://github.com/jinlife/Synology_Photos_Face_Patch/releases/download/1.6.2-0710/libsynophoto-plugin-platform.so wget --no-check-certificate https://mirror.ghproxy.com/https://github.com/jinlife/Synology_Photos_Face_Patch/releases/download/1.6.2-0710/libsynophoto-plugin-platform.so.1.0 cp -f libsynophoto-plugin-platform.so /var/packages/SynologyPhotos/target/usr/lib/ cp -f libsynophoto-plugin-platform.so.1.0 /var/packages/SynologyPhotos/target/usr/lib/ chmod +x /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so chmod +x /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0 chown SynologyPhotos:SynologyPhotos /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so chown SynologyPhotos:SynologyPhotos /var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so.1.0 synopkgctl start SynologyPhotos
> > Way 2: Refered to this command, it worked well on Mar 16, 2024 wget https://raw.githubusercontent.com/jinlife/Synology_Photos_Face_Patch/main/bin/PatchELFSharp-Linux64/PatchELFSharp -O PatchELFSharp chmod +x PatchELFSharp ./PatchELFSharp "/usr/lib/libsynosdk.so.7" "SYNOFSIsRemoteFS" "B8 00 00 00 00 C3"
> > # support face and concept
> > ./PatchELFSharp "/var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so" "_ZN9synophoto6plugin8platform20IsSupportedIENetworkEv" "B8 00 00 00 00 C3"
> > # force to support concept
> > ./PatchELFSharp "/var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so" "_ZN9synophoto6plugin8platform18IsSupportedConceptEv" "B8 01 00 00 00 C3"
> > # force no Gpu
> > ./PatchELFSharp "/var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so" "_ZN9synophoto6plugin8platform23IsSupportedIENetworkGpuEv" "B8 00 00 00 00 C3"
> > ![image](https://private-user-images.githubusercontent.com/48777459/313440045-0cfbeddc-6c79-4698-acf7-123fa99ca36e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzA1ODUsIm5iZiI6MTcxMDkzMDI4NSwicGF0aCI6Ii80ODc3NzQ1OS8zMTM0NDAwNDUtMGNmYmVkZGMtNmM3OS00Njk4LWFjZjctMTIzZmE5OWNhMzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDEwMjQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MDE3NzQ5NjgxYTk3ODY3Njc0N2M3NjQyN2Y3NjkyMTM1NGU4YjY3MmMzOTM4NGE4NGNiZThlY2VkZDZkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EfsvKIOpFWCgH0oqGPDGDk5uaIVKJlwO1rf6fkhVC5w)
> 
> I have no idea, might be other reasons.

![image](https://github.com/jinlife/Synology_Photos_Face_Patch/assets/48777459/bb8e24b6-db35-4769-acc4-d93c7f8ef303)
![image](https://github.com/jinlife/Synology_Photos_Face_Patch/assets/48777459/df18c103-82bc-468e-a63c-e3d9cc90c54a)
Hi Jinlife, could you help to check these 2 pics above, 1 has show the pics of face recognition well, and the personal space seems still wating for the update? Does it need a longer time cause it contain 30000 pic?

**Comment by gzjackar** [comment]
@jinlife  Cool, I tried the way to replace only var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so this file only, then it works now. The last time I failed maybe caused by I replace 2 files including libsynophoto-plugin-platform.so.0.1 , anyway, thanks

**Comment by jinlife** [comment]
> @jinlife Cool, I tried the way to replace only var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so this file only, then it works now. The last time I failed maybe caused by I replace 2 files including libsynophoto-plugin-platform.so.0.1 , anyway, thanks

Thanks for the update.
I usually only modify the so file without modifying so.0.1. There is no problem on my side. But some people say they can use so.0.1 successfully. It's quite strange. I don't know if this conclusion is correct. Instead, there is a problem on your side. I only changed the so file, so I don't know this kind of error occurs.

**Comment by gzjackar** [comment]
@jinlife  I reinstall the Synology Server and need to patch again, I tried in the same way, it doesn't work this time,  is the libsynophoto-plugin-platform.so  file missing in my folder? I remembered there should have libsynophoto-plugin-platform.so instead of the link?Could you help?
![image](https://github.com/jinlife/Synology_Photos_Face_Patch/assets/48777459/0e0a9891-9fef-4de0-99f0-7f50a28f8992)

![image](https://github.com/jinlife/Synology_Photos_Face_Patch/assets/48777459/733b256b-4bfd-4926-a0e9-263c67a1817b)
