### ISSUE TITLE
N100 DSM7.2.1 patch v1.6.2-0710 problem

### ISSUE THREAD

**Issue by xc-mezcal** [jinlife/Synology_Photos_Face_Patch#26]
用的rr引导DSM 7.2.1, N100的iGPU看起来还不错 [cat /sys/kernel/debug/dri/0/i915_frequency_info]
系统已打开AME的codec. 但是photos没有人物识别, 大佬我可以打这个补丁吗? 因为rr里介绍这个补丁是强制使用cpu来人物识别,但是n100自带核显,有办法不要强制使用cpu,但仍然开启人物识别功能吗?
例如您给的链接里面:

```
./PatchELFSharp "/usr/lib/libsynosdk.so.7" "SYNOFSIsRemoteFS" "B8 00 00 00 00 C3"
# support face and concept
./PatchELFSharp "/var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so" "_ZN9synophoto6plugin8platform20IsSupportedIENetworkEv" "B8 00 00 00 00 C3"
# force to support concept
./PatchELFSharp "/var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so" "_ZN9synophoto6plugin8platform18IsSupportedConceptEv" "B8 01 00 00 00 C3"
# force no Gpu
./PatchELFSharp "/var/packages/SynologyPhotos/target/usr/lib/libsynophoto-plugin-platform.so" "_ZN9synophoto6plugin8platform23IsSupportedIENetworkGpuEv" "B8 00 00 00 00 C3"
```
注释掉最后一行force no GPU 相关, 能够work吗?

还是说有别的说法,不用这么麻烦直接打`libsynophoto-plugin-platform.so` gpu也会被调用? 谢谢大佬!!!

**Comment by jinlife** [comment]
想用N100的话只能用SA6400的魔改过核显驱动的群晖型号，除了这个版本，群晖其他型号的Linux核心只有4.4版本，过时的代码，无法支持新CPU的核显驱动，N100的核显是驱动不起来的，别说人脸识别了，视频解码也不行的。像SA6400的Linux是5.x版本，新点，有人魔改把核显驱动加进这个群晖版本了，这样N100的核显能驱动起来。核显已经驱动了之后，有可能视频解码能用，人脸还是不能用，可能是人脸识别核心代码的问题，这个没时间去研究了，建议打个补丁算了。

核显驱动跟补丁没关系，如果搞不定驱动那就只能用补丁。要么用核显，要么不用，仅注释掉最后一行没用的。

这个补丁的主要作用是让不能正常使用核显驱动的CPU也能人脸识别，不管是老的或新的CPU。

**Comment by naah69** [comment]
> 想用N100的话只能用SA6400的魔改过核显驱动的群晖型号，除了这个版本，群晖其他型号的Linux核心只有4.4版本，过时的代码，无法支持新CPU的核显驱动，N100的核显是驱动不起来的，别说人脸识别了，视频解码也不行的。像SA6400的Linux是5.x版本，新点，有人魔改把核显驱动加进这个群晖版本了，这样N100的核显能驱动起来。核显已经驱动了之后，有可能视频解码能用，人脸还是不能用，可能是人脸识别核心代码的问题，调用不到驱动，这个没时间去研究了，建议打个补丁算了。
> 
> 核显驱动跟补丁没关系，如果搞不定驱动那就只能用补丁。要么用核显，要么不用，仅注释掉最后一行没用的。
> 
> 这个补丁的主要作用是让不能正常使用核显驱动的CPU也能人脸识别，不管是老的或新的CPU。

@jinlife 大佬我使用sa6400的rr引导，现在photos人脸默认用cpu了，我想使用gpu进行调用，用这个能设置强制gpu吗
