### ISSUE TITLE
Need patch for Photos v.1.7.0-0794

### ISSUE THREAD

**Issue by flashliao** [jinlife/Synology_Photos_Face_Patch#27]
DSM 7.2.2.2 just can install v.1.7.0-0794,can not install V1.6.0-0629.
There is a new version of Photos, could you release a patch for it? Thanks!

**Comment by jinlife** [comment]
It seems the the automatic patch has issues with old Synology, I'm working on it.
But you could also try to patch it by yourself, please check https://github.com/jinlife/Synology_Photos_Face_Patch/tree/main/bin

**Comment by jinlife** [comment]
Released, 
it seems the new so file is the same as 1.6.0.
