### ISSUE TITLE
大神 你是唯一一个说明白这个事的。

### ISSUE THREAD

**Issue by bovey1** [jinlife/Synology_Photos_Face_Patch#3]
我是I5 3470 CPU
物理机的时候 人脸识别是完全ok的（因为可以调用核显）。
做成虚拟机后就完全失效（核显没有直通）
换过 libsynophoto-plugin-detection.so 文件也是无效。
请大神看看这个文件是不是也有能禁用GPU的地方呢？这是 Momets的人脸识别
也是6.几的群晖。

**Comment by jinlife** [comment]
moments没兴趣研究了。哪个detection应该没有跳过GPU，可能只是老群晖，还没升级而已，碰巧能用。
你有兴趣可以按我的博客的方式去找找看，有没有类似的代码。
