### ISSUE TITLE
问下918下有办法用gpu识别吗

### ISSUE THREAD

**Issue by swhoro** [jinlife/Synology_Photos_Face_Patch#4]
pve虚拟机 j4125cpu 直通核显给黑群晖ds918+
可以用jellyfin做硬解
问下有办法直接调用gpu做识别吗

**Comment by jinlife** [comment]
当然可以，J4125带核显，918+群晖能用的。你可以网上找找PVE的教程。有不少。
能用核显还是用核显，起码不用担心升级的问题。这个补丁如果Photos升级了，可能就失效了，需要重新修改。

**Comment by swhoro** [comment]
> 当然可以，J4125带核显，918+群晖能用的。你可以网上找找PVE的直通教程。有不少，貌似有个地址位置的问题，设定好就行。 能用核显还是用核显，起码不用担心升级的问题。这个补丁如果Photos升级了，可能就失效了，需要重新修改。

谢谢回复
但是不知道怎么回事，直通核显后经常cpu占用巨高，内存占用巨高，最终导致整个机器卡死
后来是给lxc的ubuntu容器核显，在那上面做硬解了
