### ISSUE TITLE
群晖发布了新的0263版本，能否更新一下github库呢

### ISSUE THREAD

**Issue by 1264038890** [jinlife/Synology_Photos_Face_Patch#5]
大佬，群晖发布了新的0263版本，能否更新一下github呢

**Comment by jinlife** [comment]
这个不知道更新机制咋样，我这边的918+还没动静，没看到套件更新。网页发布比较快？

**Comment by 1264038890** [comment]
> 这个不知道更新机制咋样，我的918+测试动静，没看到更新网页。比较快发布？

https://archive.synology.com/download/Package/SynologyPhotos/1.2.0-0263
这里可以下载

**Comment by jinlife** [comment]
呃，发现里面还要AME 2.0支持新的格式,然后从 Advanced Media Extensions (AME) 2.0 及以上版本开始，您必须登录 Synology Account 才能授权下载 HEVC 及 AAC Codec。 这黑裙不好混了啊。

**Comment by 1264038890** [comment]
> 呃，发现里面还要AME 2.0支持新的格式,然后从 Advanced Media Extensions (AME) 2.0 及以上版本开始，您必须登录 Synology Account 才能授权下载 HEVC 及 AAC Codec。 这黑裙不好混了啊。

也就是说现在没办法用cpu来人脸识别了吗？群晖账户的话倒是没什么关系，xibai就可以解决了。主要是想知道现在还能破解吗

**Comment by 1264038890** [comment]
> 这个跟人脸识别没关系，只是Photos支持HEVC格式，还有AAC Codec在VideoStation的支持，都需要靠这个AME2.0的基础库。 要洗白成能在群晖的官方网站注册才行，现在有很多便宜洗白码都不能在中国用，都是什么土耳其的。 光升级Photos估计缺支持HEVC格式的功能。
> 
> 你要能用显卡最好用显卡，只有硬件完全不支持才需要这个补丁。例如一些老掉牙的或者太新的硬件。 破解没啥问题，放下载里面了，可以试试，建议备份。

哦哦，懂了。
不过我记得只要半洗白就可以登陆群晖账户吧。我之前有一次sn和mac不对应，也是可以登录群晖账户的，但是不能登qc，一登qc就会把群晖账户挤下来，而只是登群晖账户是没事的。使用AME2.0的基础库的话，我的想法是应该只需要能登录账户就行了，不需要绑定吧（猜测）？
还有就是不知道未来能不能高版本的video station和photos搭配低版本ame使用。我现在就是dsm7.1-42621（rc）只能安装ame1.1.2版本，而2.0的ame需要正式版7.1才能装。我手头只有rc版的引导，所以没办法升级到正式版。但是photos却可以安装最新版的，即低版本ame搭配最新版的photos使用。

**Comment by jinlife** [comment]
可能能用，手动强制用spk升级会有不兼容的风险，最好等套件自动更新。群晖会管理这个兼容性问题。 那个AME2确实只能7.1版本用。等其他大神能不能改loader去支持7.1吧。一般没有太大的版本的升级，支持应该没问题的。
另外这个AME2.0好像能在下面地址下载到，那可能只是麻烦点吧，还是手动能装的。 洗白登录就方便点，自动更新套件。https://archive.synology.com/download/Package/CodecPack/2.0.0-1017

**Comment by 1264038890** [comment]
> 可能能用，手动强制用spk升级会有不兼容的风险，最好等套件自动更新。群晖会管理这个兼容性问题。 那个AME2确实只能7.1版本用。等其他大神能不能改loader去支持7.1吧。一般没有太大的版本的升级，支持应该没问题的。 另外这个AME2.0好像能在下面地址下载到，那可能只是麻烦点吧，还是手动能装的。 洗白登录就方便点，自动更新套件。https://archive.synology.com/download/Package/CodecPack/2.0.0-1017

7.1rc版的引导已经有了，我目前就在用。
正式版的引导目前还没有消息
你发的那个我试了，不行，要正式版才能安装，版本号不匹配

**Comment by zhonghaoyun240** [comment]
> > 可能能用，手动强制用spk升级会有不兼容的风险，最好等套件自动更新。群晖会管理这个兼容性问题。 那个AME2确实只能7.1版本用。等其他大神能不能改loader去支持7.1吧。一般没有太大的版本的升级，支持应该没问题的。 另外这个AME2.0好像能在下面地址下载到，那可能只是麻烦点吧，还是手动能装的。 洗白登录就方便点，自动更新套件。https://archive.synology.com/download/Package/CodecPack/2.0.0-1017
> 
> 
> 
> 7.1rc版的引导已经有了，我目前就在用。
> 
> 正式版的引导目前还没有消息
> 
> 你发的那个我试了，不行，要正式版才能安装，版本号不匹配

正式版能用吗？你那引导
