### ISSUE TITLE
Reverse Patch

### ISSUE THREAD

**Issue by benna1990** [jinlife/Synology_Photos_Face_Patch#7]
Hi,

I installed the latest patch but face recognization is still not working. 
Is it possible te reverse/remove te patch by any change?

Thanks, Benjamin

**Comment by jinlife** [comment]
It depends on how you apply the patch. 
If you just overwrite the .so file, then you have to manually back it up before.
But if you are using PatchElfSharp to patch it, then it will automatically generate a xxx.so.bak file aside, you could revert it with this bak file.

Or you could just uninstall Synology Photos and install it again to revert it.
