### ISSUE TITLE
大神，42962用不了

### ISSUE THREAD

**Issue by nikkzy** [jinlife/Synology_Photos_Face_Patch#8]
ds918，42962无法正确识别，是不是群晖屏蔽了修复补丁？

**Comment by wudizz** [comment]
同问

**Comment by jinlife** [comment]
是Photos还是那个libsynosdk？
Photos应该只跟Photos的版本有关系。 libsynosdk.dll 需要新破解 42962版本的。

**Comment by jinlife** [comment]
测试过没问题。
猜测可能是用户使用了不好用的显卡驱动，或者用了非常新的CPU。建议如果是pve或unraid之类，直接用虚拟显卡就行了。不要用显卡，除非能正确驱动。
